# Generated by Django 3.1.7 on 2021-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
