# Generated by Django 3.1.7 on 2021-07-17 09:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopbigProducts', '0002_auto_20210707_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
