# Generated by Django 3.1.7 on 2021-06-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneProducts', '0004_product_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
