# Generated by Django 3.1.7 on 2021-06-30 06:04

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneImages', '0001_initial'),
        ('TslCloneProducts', '0005_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_album',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='TslCloneImages.imagealbum'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ImageField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TslCloneImages.imagealbum')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
