# Generated by Django 3.1.7 on 2021-06-30 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneChannels', '0005_auto_20210612_2059'),
        ('TslCloneProducts', '0009_productimage_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='TslCloneChannels.channel'),
        ),
    ]
