# Generated by Django 3.1.7 on 2021-07-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneChannels', '0005_auto_20210612_2059'),
        ('TslCloneProducts', '0010_auto_20210630_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='channel',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='TslCloneChannels.channel'),
            preserve_default=False,
        ),
    ]
