# Generated by Django 3.1.7 on 2021-05-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default='home', max_length=100),
        ),
    ]
