# Generated by Django 3.1.7 on 2021-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneProfiles', '0003_customerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='first_line',
            new_name='line1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='second_line',
            new_name='line2',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('IN', 'India')], max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
