# Generated by Django 3.1.7 on 2021-05-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneProfiles', '0004_auto_20210531_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='title',
            new_name='type',
        ),
    ]
