# Generated by Django 3.1.7 on 2021-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneProfiles', '0005_auto_20210531_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('H', 'Home'), ('W', 'Work')], default='H', max_length=100),
        ),
    ]
