# Generated by Django 3.1.7 on 2021-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneCheckout', '0002_auto_20210530_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
