# Generated by Django 3.1.7 on 2021-05-31 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneCheckout', '0003_auto_20210530_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount_collected',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='collected_amount',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='TslCloneCheckout.order'),
        ),
    ]
