# Generated by Django 3.1.7 on 2021-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneCheckout', '0004_auto_20210531_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('cn', 'canceled'), ('cr', 'created'), ('fa', 'failed'), ('pr', 'processing'), ('ra', 'requires_action'), ('sc', 'succeeded')], default=None, max_length=2, null=True),
        ),
    ]
