# Generated by Django 3.1.7 on 2021-06-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneCheckout', '0005_auto_20210602_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
    ]
