# Generated by Django 3.1.7 on 2021-06-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneChannels', '0002_auto_20210521_0801'),
        ('TslCloneCheckout', '0006_remove_order_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='TslCloneChannels.channel'),
        ),
    ]
