# Generated by Django 3.1.7 on 2021-06-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneCheckout', '0007_order_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='channel',
        ),
        migrations.AlterUniqueTogether(
            name='orderitemstatus',
            unique_together={('order_item', 'value')},
        ),
    ]
