# Generated by Django 3.1.7 on 2021-06-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneCheckout', '0008_auto_20210604_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[('P', 'placed'), ('C', 'canceled'), ('S', 'shipped'), ('D', 'delivered')], max_length=1),
        ),
    ]
