# Generated by Django 3.1.7 on 2021-06-12 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneProfiles', '0006_auto_20210531_1544'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TslCloneProducts', '0003_auto_20210612_0421'),
        ('TslClonePayout', '0002_remove_commission_category'),
        ('TslCloneCheckout', '0009_auto_20210611_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='TslCloneProfiles.address'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='TslClonePayout.commission'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TslCloneCheckout.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='TslCloneProducts.product'),
        ),
    ]
