# Generated by Django 3.1.7 on 2021-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneCheckout', '0010_auto_20210612_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('cn', 'canceled'), ('cr', 'created'), ('fa', 'failed'), ('pr', 'processing'), ('ra', 'requires_action'), ('sc', 'succeeded')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
