# Generated by Django 3.1.7 on 2021-06-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneCheckout', '0011_auto_20210612_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('P', 'placed'), ('C', 'canceled'), ('S', 'shipped'), ('D', 'delivered')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='OrderItemStatus',
        ),
    ]
