# Generated by Django 3.1.7 on 2021-07-06 09:41

import apps.shows.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShopbigChannels', '0001_initial'),
        ('ShopbigProducts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('display_pic', models.ImageField(blank=True, default=None, null=True, upload_to=apps.shows.models.display_pic_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='ShopbigChannels.channel')),
                ('products', models.ManyToManyField(to='ShopbigProducts.Product')),
            ],
        ),
        migrations.CreateModel(
            name='IVSStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_stream_id', models.CharField(max_length=100)),
                ('is_live', models.BooleanField(blank=True, default=None, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('recording_duration', models.IntegerField(blank=True, default=None, null=True)),
                ('recording_status', models.CharField(blank=True, choices=[('S', 'Recording Start'), ('E', 'Recording End'), ('SF', 'Recording Start Failure'), ('EF', 'Recording End Failure')], default=None, max_length=2, null=True)),
                ('s3_path', models.CharField(blank=True, max_length=200, null=True)),
                ('s3_bucket', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='ShopbigChannels.channel')),
                ('show', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='ShopbigShows.show')),
            ],
        ),
    ]
