# Generated by Django 3.1.7 on 2021-06-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneChannels', '0002_auto_20210521_0801'),
        ('TslCloneShows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_stream_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('recording_status', models.CharField(choices=[('S', 'Started'), ('E', 'Ended'), ('F', 'Failed')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='TslCloneChannels.channel')),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='TslCloneShows.show')),
            ],
        ),
    ]
