# Generated by Django 3.1.7 on 2021-07-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopbigShows', '0002_auto_20210705_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowImage',
        ),
    ]
