# Generated by Django 3.1.7 on 2021-06-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneShows', '0004_auto_20210605_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ivsvideo',
            old_name='recording_s3_bucket',
            new_name='s3_bucket',
        ),
    ]
