# Generated by Django 3.1.7 on 2021-06-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneShows', '0005_auto_20210605_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ivsvideo',
            old_name='aws_stream_id',
            new_name='aws_stream',
        ),
    ]
