# Generated by Django 3.1.7 on 2021-06-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneShows', '0006_auto_20210606_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivsvideo',
            name='show',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='TslCloneShows.show'),
        ),
    ]
