# Generated by Django 3.1.7 on 2021-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneShows', '0007_auto_20210611_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivsvideo',
            name='s3_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
