# Generated by Django 3.1.7 on 2021-06-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneChannels', '0005_auto_20210612_2059'),
        ('TslCloneShows', '0008_auto_20210612_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVSStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_stream_id', models.CharField(max_length=100)),
                ('is_live', models.BooleanField(blank=True, default=None, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('recording_duration', models.IntegerField(blank=True, default=None, null=True)),
                ('recording_status', models.CharField(blank=True, choices=[('S', 'Started'), ('E', 'Ended'), ('SF', 'Start Failed'), ('EF', 'End Failed')], default=None, max_length=2, null=True)),
                ('s3_path', models.CharField(blank=True, max_length=200, null=True)),
                ('s3_bucket', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='TslCloneChannels.channel')),
                ('show', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='TslCloneShows.show')),
            ],
        ),
        migrations.DeleteModel(
            name='IVSVideo',
        ),
    ]
