# Generated by Django 3.1.7 on 2021-06-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneShows', '0009_auto_20210628_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivsstream',
            name='recording_status',
            field=models.CharField(blank=True, choices=[('S', 'Recording Start'), ('E', 'Recording End'), ('SF', 'Recording Start Failure'), ('EF', 'Recording End Failure')], default=None, max_length=2, null=True),
        ),
    ]
