# Generated by Django 3.1.7 on 2021-06-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneProducts', '0007_auto_20210630_0614'),
        ('TslCloneImages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
    ]
