# Generated by Django 3.1.7 on 2021-07-05 07:51

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopbigImages', '0003_image_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='base',
            field=models.ImageField(upload_to=apps.images.models.get_upload_path),
        ),
    ]
