# Generated by Django 3.1.7 on 2021-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopbigImages', '0004_auto_20210705_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagealbum',
            name='name',
        ),
        migrations.RemoveField(
            model_name='imagealbum',
            name='owner',
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
