# Generated by Django 3.1.7 on 2021-07-05 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShopbigImages', '0005_auto_20210705_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='ShopbigUsers.user'),
            preserve_default=False,
        ),
    ]
