# Generated by Django 3.1.7 on 2021-05-30 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TslCloneProducts', '0002_product_selling_price'),
        ('TslCloneChannels', '0002_auto_20210521_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_per_item', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('fixed_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='TslCloneProducts.category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='TslCloneChannels.channel')),
            ],
        ),
    ]
