# Generated by Django 3.1.7 on 2021-05-31 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TslClonePayout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='category',
        ),
    ]
