# Generated by Django 3.1.7 on 2021-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_connected_account',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
