# Generated by Django 3.2.5 on 2021-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopbigUsers', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seller_activated',
            field=models.BooleanField(default='1'),
        ),
    ]
