# Generated by Django 3.1.7 on 2021-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneUsers', '0004_auto_20210612_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
