# Generated by Django 3.1.7 on 2021-07-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneUsers', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_activated',
            field=models.BooleanField(default=False),
        ),
    ]
