# Generated by Django 3.1.7 on 2021-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='display_pic',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
