# Generated by Django 3.1.7 on 2021-04-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='stream',
            new_name='stream_key',
        ),
    ]
