# Generated by Django 3.1.7 on 2021-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_remove_channel_stream_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='background_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='display_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
