# Generated by Django 3.1.7 on 2021-05-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_auto_20210510_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
