# Generated by Django 3.1.7 on 2021-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_auto_20210513_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='arn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='stream_key_arn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
