# Generated by Django 3.1.7 on 2021-07-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopbigChannels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='background_pic',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='display_pic',
        ),
    ]
