# Generated by Django 3.1.7 on 2021-06-12 03:59

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('TslCloneChannels', '0002_auto_20210521_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
