# Generated by Django 3.1.7 on 2021-07-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopbigImages', '0004_auto_20210705_0751'),
        ('ShopbigChannels', '0002_auto_20210705_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image_album',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='ShopbigImages.imagealbum'),
        ),
    ]
