# Generated by Django 3.1.7 on 2021-06-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneChannels', '0003_channel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='tags',
        ),
    ]
