# Generated by Django 3.1.7 on 2021-07-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopbigImages', '0005_auto_20210705_1149'),
        ('ShopbigChannels', '0003_channel_image_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelBackgroundPicAlbumSerializer',
            fields=[
                ('imagealbum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ShopbigImages.imagealbum')),
            ],
            bases=('ShopbigImages.imagealbum',),
        ),
        migrations.CreateModel(
            name='ChannelDisplayPicAlbumSerializer',
            fields=[
                ('imagealbum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ShopbigImages.imagealbum')),
            ],
            bases=('ShopbigImages.imagealbum',),
        ),
        migrations.RemoveField(
            model_name='channel',
            name='image_album',
        ),
        migrations.AddField(
            model_name='channel',
            name='background_pic_album',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_pic_channel', to='ShopbigImages.imagealbum'),
        ),
        migrations.AddField(
            model_name='channel',
            name='display_pic_album',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_pic_channel', to='ShopbigImages.imagealbum'),
        ),
    ]
