# Generated by Django 3.1.7 on 2021-06-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TslCloneChannels', '0004_remove_channel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='arn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='stream_key_arn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
