# Generated by Django 3.1.7 on 2021-04-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20210402_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='backgroundPic',
            new_name='background_pic',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='displayPic',
            new_name='display_pic',
        ),
    ]
