# Generated by Django 3.1.7 on 2021-04-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20210402_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='video',
        ),
        migrations.AlterField(
            model_name='channel',
            name='background_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='display_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='channel.channel')),
            ],
        ),
    ]
