# Generated by Django 3.1.7 on 2021-04-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_auto_20210402_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
