# Generated by Django 3.1.7 on 2021-04-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
