# Generated by Django 3.2.5 on 2021-08-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShopbigChannels', '0002_alter_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtmp_ingest', models.CharField(max_length=500)),
                ('rtmp_key', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('FB', 'FACEBOOK'), ('YT', 'YOUTUBE'), ('CUS', 'CUSTOM')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='ShopbigChannels.channel')),
            ],
        ),
    ]
