# Generated by Django 3.1.7 on 2021-05-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210502_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='primaryImage',
            new_name='primary_image',
        ),
    ]
